# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVdoPLQZMTX1C0XUNVrlKOHdl_RtJqa3
"""

!pip install streamlit pyngrok plotly seaborn

from pyngrok import ngrok

# Paste your ngrok token here
ngrok.set_auth_token("366Hjgj2lHm3lzXxubFqcTbVx7y_3w2re6wbcGw2be51oaM2U")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import seaborn as sns
# import matplotlib.pyplot as plt
# 
# # Load Data
# df = pd.read_csv("/content/googleplaystore_cleaned.csv")
# 
# # Streamlit Page Config
# st.set_page_config(
#     page_title="App Market Analytics – Google Play Edition",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # Header Section
# # ---------------------------------
# st.title("📱 App Market Analytics – Google Play Edition")
# st.markdown("""
# Welcome to the **Google Play Store Analytics & Insights Dashboard** — a fully interactive platform designed to help you explore app trends, performance metrics, and market behavior on the Google Play Store.
# 
# ### 🔍 What You Can Explore:
# - **Category Distribution** — Identify which app categories dominate the market.
# - **Ratings & Reviews Patterns** — Understand how user feedback affects app success.
# - **Free vs Paid App Analysis** — Compare usage trends, popularity, and rating differences.
# - **Installs & Popularity Trends** — Analyze how installation counts vary across apps and categories.
# - **Top-Performing Apps** — Find the highest-rated, most-reviewed, and most-installed apps.
# - **Correlation Insights** — Discover relationships between installs, reviews, ratings, and pricing.
# 
# Use the filters in the sidebar to customize your view and uncover meaningful insights hidden within the dataset.
# """)
# 
# # Sidebar Filters
# st.sidebar.header("🔎 Filter Your View")
# 
# # Search bar
# search_query = st.sidebar.text_input("🔍 Search App Name")
# 
# # Multi-category selection
# category_multi = st.sidebar.multiselect(
#     "Select Category",
#     sorted(df["Category"].unique()),
#     default=None
# )
# 
# type_filter = st.sidebar.radio(
#     "App Type",
#     ["All", "Free", "Paid"]
# )
# 
# content_filter = st.sidebar.selectbox(
#     "Content Rating",
#     ["All"] + sorted(df["Content Rating"].unique())
# )
# 
# min_rating = st.sidebar.slider(
#     "Minimum Rating", 1.0, 5.0, 1.0, 0.1
# )
# 
# # Download button
# st.sidebar.download_button(
#     label="⬇ Download Cleaned Dataset",
#     data=df.to_csv(index=False),
#     file_name="googleplay_cleaned.csv",
#     mime="text/csv"
# )
# 
# # Apply Filters
# df_filtered = df.copy()
# 
# if search_query:
#     df_filtered = df_filtered[df_filtered["App"].str.contains(search_query, case=False, na=False)]
# 
# if category_multi:
#     df_filtered = df_filtered[df_filtered["Category"].isin(category_multi)]
# 
# if type_filter != "All":
#     df_filtered = df_filtered[df_filtered["Type"] == type_filter]
# 
# if content_filter != "All":
#     df_filtered = df_filtered[df_filtered["Content Rating"] == content_filter]
# 
# df_filtered = df_filtered[df_filtered["Rating"] >= min_rating]
# 
# # Stats After Filtering
# st.info(f"📌 Showing **{df_filtered.shape[0]} apps** after applying filters.")
# 
# # Metrics Row
# col1, col2, col3, col4 = st.columns(4)
# col1.metric("Total Apps", df_filtered.shape[0])
# col2.metric("Categories", df_filtered["Category"].nunique())
# col3.metric("Avg Rating", round(df_filtered["Rating"].mean(), 2))
# col4.metric("Total Reviews", df_filtered["Reviews"].sum())
# 
# 
# # TABS for Better Navigation
# tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9, tab10 = st.tabs([
#     "📂 Category Distribution",
#     "⭐ Reviews vs Ratings",
#     "💰 Free vs Paid",
#     "📈 Installs Analysis",
#     "🏆 Top Apps",
#     "📊 Correlation Heatmap",
#     "📉 Rating Distribution",
#     "💵 Price Analysis",
#     "📘 Category Deep Dive",
#     "⚖ App Comparison"
# ])
# 
# 
# # TAB 1 — CATEGORY DISTRIBUTION
# with tab1:
#     st.subheader("📂 Category Distribution")
# 
#     # Prepare data
#     cat_count = df_filtered["Category"].value_counts().reset_index()
#     cat_count.columns = ["Category", "Count"]
# 
#     # Sort for bar chart
#     cat_count_sorted = cat_count.sort_values(by="Count", ascending=True)
# 
# # 📊Vertical Bar Chart
# fig1 = px.bar(
#     cat_count_sorted,
#     x="Category",
#     y="Count",
#     title=" Apps Per Category",
#     color="Count",
#     color_continuous_scale="Viridis",   # 🔥 Gradient color upgrade
#     template="plotly_white",
#     text="Count",
# )
# 
# # Make bars prettier & rounded
# fig1.update_traces(
#     textposition="outside",
#     marker=dict(
#         line=dict(width=1, color="black"),
#         opacity=0.9
#     ),
#     hovertemplate='<b>%{x}</b><br>Apps: %{y}<extra></extra>'
# )
# 
# # Update Layout
# fig1.update_layout(
#     title=dict(x=0.5, font=dict(size=26, family="Arial Black")),
#     xaxis_title="Category",
#     yaxis_title="Number of Apps",
#     plot_bgcolor="rgba(0,0,0,0)",
#     paper_bgcolor="rgba(0,0,0,0)",
#     margin=dict(l=40, r=40, t=80, b=120),
#     height=650,
# 
#     # Rotate category labels
#     xaxis=dict(
#         tickangle=45,
#         tickfont=dict(size=12)
#     )
# )
# 
# st.plotly_chart(fig1, use_container_width=True)
# 
# # 🥧 Pie Chart (Pastel Colors)
# st.subheader(" Category Share ")
# 
# fig2 = px.pie(
#     cat_count,
#     names="Category",
#     values="Count",
#     title="Category Percentage Share",
#     color_discrete_sequence=px.colors.qualitative.Pastel,  # 💡 changed color theme
#     hole=0.35
# )
# 
# fig2.update_layout(
#     title=dict(x=0.5, font=dict(size=22)),
#     margin=dict(l=40, r=40, t=80, b=40),
# )
# 
# fig2.update_traces(
#     textposition="inside",
#     textinfo="percent+label"
# )
# 
# st.plotly_chart(fig2, use_container_width=True)
# 
# # TAB 2 — REVIEWS VS RATINGS
# with tab2:
#     st.subheader("⭐ Reviews vs Ratings")
#     fig2 = px.scatter(df_filtered, x="Reviews", y="Rating",
#                       size="Installs", color="Category",
#                       hover_name="App", log_x=True,
#                       title="Reviews vs Ratings (Log Scale)",
#                       template="plotly_white")
#     st.plotly_chart(fig2, use_container_width=True)
# 
# # TAB 3 — FREE VS PAID ANALYSIS
# with tab3:
#     st.subheader("💰 Free vs Paid Analysis")
#     colA, colB = st.columns(2)
# 
#     type_count = df_filtered["Type"].value_counts().reset_index()
#     type_count.columns = ["Type", "Count"]
# 
#     fig_bar = px.bar(type_count, x="Type", y="Count",
#                      title="Free vs Paid App Count",
#                      color="Type", template="plotly_white")
#     colA.plotly_chart(fig_bar, use_container_width=True)
# 
#     fig_pie = px.pie(type_count, names="Type", values="Count",
#                      title="Free vs Paid Share")
#     colB.plotly_chart(fig_pie, use_container_width=True)
# 
#     st.subheader("📦 Rating Comparison")
#     fig_box = px.box(df_filtered, x="Type", y="Rating",
#                      title="Ratings Distribution (Free vs Paid)",
#                      template="plotly_white")
#     st.plotly_chart(fig_box, use_container_width=True)
# 
# # TAB 4 — INSTALLS ANALYSIS
# with tab4:
#     st.subheader("📈 Installs Analysis")
#     top_installs = df_filtered.sort_values(by="Installs", ascending=False).head(15)
# 
#     fig3 = px.bar(top_installs, x="App", y="Installs",
#                   color="Category", title="Top 15 Apps by Installs",
#                   template="plotly_white")
#     st.plotly_chart(fig3, use_container_width=True)
# 
# # TAB 5 — TOP APPS SECTION
# with tab5:
#     st.subheader("🏆 Top Apps Ranking")
#     colT1, colT2 = st.columns(2)
# 
#     top_reviews = df_filtered.sort_values(by="Reviews", ascending=False).head(10)
#     top_installs = df_filtered.sort_values(by="Installs", ascending=False).head(10)
# 
#     colT1.write("### 🔝 Top 10 Apps (Reviews)")
#     colT1.dataframe(top_reviews[['App', 'Category', 'Reviews', 'Rating']])
# 
#     colT2.write("### 📥 Top 10 Apps (Installs)")
#     colT2.dataframe(top_installs[['App', 'Category', 'Installs', 'Rating']])
# 
# # TAB 6 — CORRELATION HEATMAP
# with tab6:
#     st.subheader("📊 Correlation Heatmap")
#     fig, ax = plt.subplots(figsize=(10, 4))
#     sns.heatmap(df_filtered.corr(numeric_only=True), annot=True, cmap="coolwarm")
#     st.pyplot(fig)
# 
# # TAB 7 — RATING DISTRIBUTION
# with tab7:
#     st.subheader("📉 Rating Distribution")
#     fig_hist = px.histogram(df_filtered, x="Rating", nbins=30,
#                             title="Distribution of App Ratings",
#                             template="plotly_white")
#     st.plotly_chart(fig_hist, use_container_width=True)
# 
#     fig_kde = px.density_contour(df_filtered, x="Rating",
#                                  title="Rating KDE Density Plot")
#     st.plotly_chart(fig_kde, use_container_width=True)
# 
# 
# # TAB 8 — PRICE ANALYSIS
# with tab8:
#     st.subheader("💵 Price Analysis (Paid Apps Only)")
#     paid_apps = df_filtered[df_filtered["Type"] == "Paid"]
# 
#     if len(paid_apps) == 0:
#         st.warning("No paid apps found based on your current filters.")
#     else:
#         fig_price = px.histogram(paid_apps, x="Price", nbins=40,
#                                  title="Price Distribution for Paid Apps",
#                                  template="plotly_white")
#         st.plotly_chart(fig_price, use_container_width=True)
# 
#         fig_price_box = px.box(paid_apps, y="Price",
#                                title="Price Range for Paid Apps")
#         st.plotly_chart(fig_price_box, use_container_width=True)
# 
# 
# # TAB 9 — CATEGORY DEEP DIVE
# with tab9:
#     st.subheader("📘 Category Deep Dive")
# 
#     selected_category = st.selectbox("Choose a Category", sorted(df["Category"].unique()))
# 
#     df_cat = df[df["Category"] == selected_category]
# 
#     st.write(f"### 📌 Insights for Category: **{selected_category}**")
#     st.metric("Total Apps", df_cat.shape[0])
#     st.metric("Average Rating", round(df_cat["Rating"].mean(), 2))
#     st.metric("Total Installs", df_cat["Installs"].sum())
# 
#     fig_cd = px.bar(df_cat.sort_values("Installs", ascending=False).head(10),
#                     x="App", y="Installs", color="Rating",
#                     title=f"Top Apps in {selected_category}",
#                     template="plotly_white")
#     st.plotly_chart(fig_cd, use_container_width=True)
# 
# # TAB 10 — APP COMPARISON TOOL
# with tab10:
#     st.subheader("⚖ Compare Two Apps")
# 
#     app_list = sorted(df["App"].unique())
# 
#     app1 = st.selectbox("Select App 1", app_list)
#     app2 = st.selectbox("Select App 2", app_list)
# 
#     df_app1 = df[df["App"] == app1]
#     df_app2 = df[df["App"] == app2]
# 
#     st.write("### 📊 Comparison Table")
#     st.dataframe(pd.concat([df_app1, df_app2])[["App", "Category", "Rating", "Reviews", "Installs", "Price"]])
# 
#     fig_cmp = px.bar(pd.concat([df_app1, df_app2]),
#                      x="App", y="Rating", color="App",
#                      title="Rating Comparison")
#     st.plotly_chart(fig_cmp, use_container_width=True)
# 
# 
# # Footer
# st.markdown("---")
# st.markdown("### ✔ Fully Interactive Dashboard — Powered by Streamlit")
#

!streamlit run app.py &>/dev/null &

from pyngrok import ngrok

# Terminate any existing ngrok tunnels
ngrok.kill()

public_url = ngrok.connect(8501)
print("Your Streamlit App URL:", public_url)